version: 1
default_environment: dev-marieke
project_id: fd2cdee4-b349-4138-b528-ddb6146a2449
environments:
- name: dev-marieke
- name: staging
- name: prod
schedules:
- name: daily-refresh
  job: daily-refresh-job
  interval: '@daily'  # Can be @daily, @hourly, etc., or a cron-based interval
jobs:
- name: daily-refresh-job
  tasks:
  # Update this section to include any EL jobs or other
  # commands that you'd like to run:
  - tap-gitlab target-snowflake
  - dbt-snowflake:run
  - dbt-snowflake:test