version: 1
default_environment: dev-marieke
project_id: fd2cdee4-b349-4138-b528-ddb6146a2449
environments:
- name: dev-marieke
- name: staging
- name: prod
schedules:
- name: daily-refresh
  interval: '@daily'  # Can be @daily, @hourly, etc., or a cron-based interval
  job: daily-refresh-jobch
jobs:
- name: daily-refresh-job
  tasks:
  # Update this section to include any EL jobs or other
  # commands that you'd like to run:
  - tap-sevenrooms target-redshift
plugins:
  extractors:
  - name: tap-sevenrooms
    variant: uptilab2
    pip_url: git+https://github.com/uptilab2/tap-sevenrooms.git
  loaders:
  - name: target-redshift
    variant: transferwise
    pip_url: git+https://github.com/menzenski/pipelinewise-target-redshift.git@856f6390805e4d64e743901b5f585f01a93df6a1

